on:
  push:
    branches: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: tests
        uses: actions/checkout@v3

      - name: setUpJava
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: test2
        run: mvn test

